# Generated by Django 5.2.8 on 2026-03-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('officer', 'Officer')], default='citizen', max_length=20),
            preserve_default=False,
        ),
    ]
