# Generated by Django 5.2.8 on 2026-03-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_complaint_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='department',
            field=models.CharField(max_length=100),
        ),
    ]
