# Generated by Django 5.2.8 on 2026-03-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_complaint_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
