# Generated by Django 5.2.8 on 2026-03-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_complaint_address_complaint_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('road', 'Road Issue'), ('water', 'Water Problem'), ('electricity', 'Electricity'), ('garbage', 'Garbage'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='update',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='updates/'),
        ),
        migrations.AlterField(
            model_name='update',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], max_length=20),
        ),
    ]
